services:
  eureka:
    image: ${HS_EUREKA_IMAGE:-mhws/hs-eureka:latest}
    ports:
      - ${HS_EUREKA_PORT:-8761}:8761

  hs-files-compressor:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - ${HS_FILES_COMPRESSOR_PORT:-8769}:8769