spring:
  application:
    name: files-compressor
  config:
    import: optional:configserver:${CONFIGSERVER_URI:http://localhost:8888}
  cloud:
    config:
      enabled: false
  profiles:
    active: local