server:
  port: 8769

app:
  paintings:
    repository:
      fs:
        mount: ${HS_FILES_PAINTINGS_VOLUME:./pictures}
    client:
      server-urls:
        - ws://localhost:8767


#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        web: DEBUG
#      hibernate: ERROR
